version = 0.1
[default.deploy.parameters]
stack_name = "contactsmeetup-app"
resolve_s3 = true
s3_prefix = "contactsmeetup-app"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
