AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A SAM/CF template to create contact function, API and DynamoDB table


Globals:
  Function:
    Timeout: 25
Resources:
  # lambda function to save contact to contacts table
 ContactFn:
    Type: AWS::Serverless::Function
    Properties:
      Description: function to perform CRUD operation on contacts 
      FunctionName: ContactHandler
      Architectures:
        - x86_64
      CodeUri: .
      Handler: contactAPI.lambda_handler
      Runtime: python3.10
      Timeout: 15
      MemorySize: 128   # defauld 128mb, upto 10GB
      Policies: 
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: contacts    # replace table name with !Ref when integrate with final SAM/CF template
      Events:
        createConteact:
          Type: Api
          Properties:
            Path: /createContact
            Method: post
            RestApiId: !Ref ContactApi
            # Auth:
            #   Authorizer: OAuth2
        getConteacts:
          Type: Api
          Properties:
            Path: /allContacts
            Method: get
            RestApiId: !Ref ContactApi
            # Auth:
            #   Authorizer: OAuth2
        getConteact:
          Type: Api
          Properties:
            Path: /contact
            Method: get
            RestApiId: !Ref ContactApi
            # Auth:
            #   Authorizer: OAuth2
        deleteConteact:
          Type: Api
          Properties:
            Path: /deleteContact
            Method: delete
            RestApiId: !Ref ContactApi
            # Auth:
            #   Authorizer: OAuth2

 # Rest API that integrate with lambda fuction to create/save contact in contacts table
 ContactApi:
    Type: AWS::Serverless::Api
    Properties:
      Description: Rest API to call Contact lambda function
      Name: ContactAPI
      StageName: dev
      EndpointConfiguration:
        Type: REGIONAL
      FailOnWarnings: True
      # Auth:
      #   Authorizers:
      #     OAuth2:
      #       AuthorizationScopes:
      #         - email
      #       UserPoolArn: !GetAtt ContactUserPool.Arn

Outputs:
  contactFunction:
    Description: display the function name created by SAM
    Value: !Ref ContactFn
  createContactAPIEndpoint:
    Description: "Create Contact API dev stage Endpoint"
    Value: !Sub "https://${ContactApi}.execute-api.${AWS::Region}.amazonaws.com/dev/createContact"
  getAllContactsAPIEndpoint:
    Description: "get all Contacts API dev stage Endpoint"
    Value: !Sub "https://${ContactApi}.execute-api.${AWS::Region}.amazonaws.com/dev/allContacts"
  getContactAPIEndpoint:
    Description: "get a  Contact by phone API dev stage Endpoint"
    Value: !Sub "https://${ContactApi}.execute-api.${AWS::Region}.amazonaws.com/dev/contact"
  deleteContactAPIEndpoint:
    Description: "delete a  Contact by phone API dev stage Endpoint"
    Value: !Sub "https://${ContactApi}.execute-api.${AWS::Region}.amazonaws.com/dev/deleteContact" 
    
  